### ISSUE TITLE
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

### ISSUE THREAD

**Issue by hrnbot** [TooTouch/MemSeg#18]
i am training on single class label of custom data and receiving error like this ,

```
my config file 
EXP_NAME: MemSeg
SEED: 42

DATASET:
  datadir: dataset_ind_1
  texture_source_dir: dtd/images
  anomaly_mask_info: anomaly_mask.json
  target: good
  resize:
    - 704 # height
    - 480 # width
  structure_grid_size: 1
  transparency_range:
    - 0.15 # under bound
    - 1. # upper bound
  perlin_scale: 6
  min_perlin_scale: 0
  perlin_noise_threshold: 0.5

DATALOADER:
  batch_size: 8
  num_workers: 0

MEMORYBANK:
  nb_memory_sample: 30

MODEL:
  feature_extractor_name: resnet18

TRAIN:
  batch_size: 8
  num_training_steps: 5000
  l1_weight: 0.6
  focal_weight: 0.4
  focal_alpha: null
  focal_gamma: 4
  use_wandb: True

OPTIMIZER:
  lr: 0.003
  weight_decay: 0.0005

SCHEDULER:
  min_lr: 0.0001
  warmup_ratio: 0.1
  use_scheduler: True

LOG:
  log_interval: 1
  eval_interval: 100

RESULT:
  savedir: saved_models
```
